name: Build and deploy Node.js app to Azure Web App - recipesss

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2

        - name: Setup Node.js environment
          uses: actions/setup-node@v2
          with:
            node-version: '16'

        - name: Install backend dependencies
          run: |
            cd backend
            npm install

        - name: Install frontend dependencies
          run: |
            cd frontend
            npm install

        
      # Optional: Add step to run tests here (Jest, Mocha, etc.)
      
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: nodejs-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: nodejs-app
          path: .
          
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'recipesss'
          slot-name: 'Production'
          publish-profile: ${{ secrets.recipesss }}
          package: .
